Repository DevByDJ/Database-Engineering-Project, pull requests merged in 2023-04, with the labels that each got.

#21 Create 3 .csv files
  Internship.csv file
  company.csv file
  tag.csv file
Labels: Database

#26 Brandon's test branch
  Internship.csv file
  company.csv file
  package-lock.json
  tag.csv file
Labels: Database

#29 Connected Postgres Database -- Fixed Register Page
  database.js
  package-lock.json
  package.json
  routes/dashboard.js
  routes/login.js
  routes/register.js
  scripts/dashboard.js
  scripts/login.js
  scripts/register.js
  server.js
  tables/company/controller.js
  tables/company/queries.js
  tables/internship/controller.js
  tables/internship/queries.js
  tables/internship_survey/controller.js
  tables/internship_survey/queries.js
  tables/student/controller.js
  tables/student/queries.js
  tables/tag/controller.js
  tables/tag/queries.js
  views/register.ejs
Labels: Back-End, Database

#31 Adding file containing sql statements for future
  dbConnection.env
  sqlStatements.pgsql
Labels: Back-End, Database

#39 Resolved the following issues:
  app.js
  routes/survey.js
  routes/tag.js
  routes/view.js
  sqlStatements.pgsql
  tables/internship_survey/controller.js
  tables/internship_survey/queries.js
  tables/student/queries.js
  tables/tag/controller.js
  tables/tag/queries.js
  tables/viewTable/controller.js
  tables/viewTable/queries.js
Labels: enhancement, Back-End, Database

#40 Nick's test branch
  app.js
  package-lock.json
  package.json
  routes/dashboard.js
  routes/db.js
  routes/sort.js
  server.js
  views/dashboard.ejs
  views/login.ejs
Labels: enhancement, Front-End, Back-End

#42 Kevin's-test-branch
  app.js
  routes/company.js
  routes/dashboard.js
  routes/internship.js
  routes/tag.js
  tables/company/controller.js
  tables/company/queries.js
  tables/internship/controller.js
  tables/internship/queries.js
Labels: Back-End, Database

#43 bug fixes
  tables/internship/controller.js
Labels: Back-End, Database

#44 Validates the User Against the DB #11
  tables/student/controller.js
  tables/student/queries.js
Labels: Back-End, Database

#45 background colors to fgcu colors
  public/loginStyle.css
  public/style.css
Labels: Front-End
